### ISSUE TITLE
Is it possible to change the model structure?

### ISSUE THREAD

**Issue by PPPNut** [OpenNMT/CTranslate2#1083]
when i use `ct2-opennmt-py-converter --model_path model_step_22000.pt --output_dir ende_ctranslate --quantization int8`

```
Traceback (most recent call last):
  File "/usr/local/bin/ct2-opennmt-py-converter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/opennmt_py.py", line 325, in main
    OpenNMTPyConverter(args.model_path).convert_from_args(args)
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/opennmt_py.py", line 152, in _load
    checkpoint = torch.load(self._model_path, map_location="cpu")
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK
```

```
# Corpus opts:
data:
    corpus_1:
        path_src: ./data/spoc/src-train.txt
        path_tgt: ./data/spoc/tgt-train.txt
    valid:
        path_src: ./data/spoc/src-val.txt
        path_tgt: ./data/spoc/tgt-val.txt

## Where the samples will be written
save_data: ./model/transformer
## Where the vocab(s) will be written
src_vocab: ./model/transformer/src.vocab
tgt_vocab: ./model/transformer/src.vocab
src_vocab_size: 5000
tgt_vocab_size: 5000
share_vocab: true

# Where to save the checkpoints
save_model: ./model/transformer/model
save_checkpoint_steps: 1000
train_steps: 1000000
valid_steps: 1000

# Batching
bucket_size: 1024
world_size: 1
gpu_ranks: [0]
num_workers: 1
batch_type: "tokens"
batch_size: 512
valid_batch_size: 512
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp16"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 2
dec_layers: 2
heads: 8
hidden_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
```

**Comment by guillaumekln** [comment]
The error message could mean that the `.pt` file is corrupted.

Does it work when you load this model in OpenNMT-py for translation?

**Comment by PPPNut** [comment]
Yes, it works perfectly fine when I use Openmtt-py, but not when I use ct2-openmtt-py-converter.
The case on the official website can be used, but my model can not be used. Is it because I changed the number of layers in the model?

**Comment by guillaumekln** [comment]
The number of layers should be fine. You get a specific error message if the model architecture is not supported.

What OpenNMT-py version did you use to train the model? Do you have the same version installed when running `ct2-opennmt-py-converter`?

**Comment by PPPNut** [comment]
I'm using opennmt-py 3.0.4.Is the version too high?

**Comment by guillaumekln** [comment]
I'm not aware of any incompatibility with the latest OpenNMT-py version.

Is it possible for you to share this model? I can work on this issue if I can easily reproduce the error.

**Comment by PPPNut** [comment]
I found the reason. I used ct2-opennmt-py-converter without using onmt_release_model to process the model. it works fine now. Thank you so much for your enthusiasm in solving the problem!

**Comment by guillaumekln** [comment]
This sounds surprising to me. There should be no need to release the model first. Let's see if others are facing the same issue.
