### ISSUE TITLE
Plans to support "mlp" feature merge embeddings?

### ISSUE THREAD

**Issue by ArtanisTheOne** [OpenNMT/CTranslate2#1112]
Tried to convert a transformer model from OpenNMT-py which uses "mlp" for it's embeddings but MLP hasn't been incorporated into conversion, so I assume it's not supported in CTranslate2. 
```python
onmt_release_model --model ./saves/model_step_52000.pt --format ctranslate2 --quantization int8 --output ./ct2
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\onmt_release_model.exe\__main__.py", line 7, in <module>
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\onmt\bin\release_model.py", line 30, in main
    converter.convert(opt.output, force=True,
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\ctranslate2\converters\converter.py", line 89, in convert
    model_spec = self._load()
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\ctranslate2\converters\opennmt_py.py", line 175, in _load
    return _get_model_spec_seq2seq(
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\ctranslate2\converters\opennmt_py.py", line 81, in _get_model_spec_seq2seq
    embeddings_merge=_SUPPORTED_FEATURES_MERGE[feat_merge],
KeyError: 'mlp'
```

Wanted to trial and error mlp against the normal concat to compare and contrast how it may affect results, as they seemed to be promising

**Comment by guillaumekln** [comment]
> as they seemed to be promising

Do you have some results to share? I would think that "concat" is good enough in most cases.

**Comment by ArtanisTheOne** [comment]
I wasn't able to actually test it but I can conduct some experiments and compare using OpenNMT-py, reason I didn't test it is because my entire testing pipeline is in CTranslate2 - found "mlp" embeddings to be an interesting concept when I discovered them, hence my curiosity.
