### ISSUE TITLE
It works fine, but gives an error.

### ISSUE THREAD

**Issue by mayjack0312** [OpenNMT/CTranslate2#1214]
- Excuse me, after I run the `whisper-ctranslate2 test.mp3 --task transcribe --language Chinese` command, I can successfully recognize the voice and generate the corresponding file, but what is the reason for the following error?
- report error：
```
Traceback (most recent call last):
  File "/usr/local/bin/whisper-ctranslate2", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/src/whisper_ctranslate2/whisper_ctranslate2.py", line 517, in main
    result = Transcribe().inference(
  File "/usr/local/lib/python3.10/dist-packages/src/whisper_ctranslate2/transcribe.py", line 125, in inference
    segments, info = model.transcribe(
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 236, in transcribe
    audio = decode_audio(audio, sampling_rate=sampling_rate)
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/audio.py", line 45, in decode_audio
    with av.open(input_file, metadata_errors="ignore") as container:
  File "av/container/core.pyx", line 401, in av.container.core.open
  File "av/container/core.pyx", line 272, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 292, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
```
- My system is Ubuntu , The python version is 3.10.6

**Comment by guillaumekln** [comment]
This is the wrong repo for this issue.

It looks like you are using this project:

https://github.com/Softcatala/whisper-ctranslate2
