### ISSUE TITLE
Cannot convert Falcon 40B (but Falcon 7B works)

### ISSUE THREAD

**Issue by juliensalinas** [OpenNMT/CTranslate2#1277]
Hello team,

I can successfully convert Falcon 7B with the following command: `ct2-transformers-converter --model tiiuae/falcon-7b-instruct --quantization float16 --output_dir falcon-7b-instruct --trust_remote_code`

However it fails for Falcon 40B: `ct2-transformers-converter --model tiiuae/falcon-40b-instruct --quantization float16 --output_dir falcon-40b-instruct --trust_remote_code`

Error: `AttributeError: 'RWConfig' object has no attribute 'multi_query'`

Here is the full stacktrace:

```
ct2-transformers-converter --model tiiuae/falcon-40b-instruct --quantization float16 --output_dir falcon-40b-instruct --trust_remote_code
Downloading (…)lve/main/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████| 658/658 [00:00<00:00, 201kB/s]
Downloading (…)/configuration_RW.py: 100%|████████████████████████████████████████████████████████████████████████████████| 2.51k/2.51k [00:00<00:00, 806kB/s]
A new version of the following files was downloaded from https://huggingface.co/tiiuae/falcon-40b-instruct:
- configuration_RW.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Downloading (…)main/modelling_RW.py: 100%|████████████████████████████████████████████████████████████████████████████████| 47.1k/47.1k [00:00<00:00, 200kB/s]
A new version of the following files was downloaded from https://huggingface.co/tiiuae/falcon-40b-instruct:
- modelling_RW.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Downloading (…)model.bin.index.json: 100%|███████████████████████████████████████████████████████████████████████████████| 39.3k/39.3k [00:00<00:00, 18.1MB/s]
Downloading (…)l-00001-of-00009.bin: 100%|████████████████████████████████████████████████████████████████████████████████| 9.50G/9.50G [00:18<00:00, 518MB/s]
Downloading (…)l-00002-of-00009.bin: 100%|████████████████████████████████████████████████████████████████████████████████| 9.51G/9.51G [00:18<00:00, 508MB/s]
Downloading (…)l-00003-of-00009.bin: 100%|████████████████████████████████████████████████████████████████████████████████| 9.51G/9.51G [00:22<00:00, 427MB/s]
Downloading (…)l-00004-of-00009.bin: 100%|████████████████████████████████████████████████████████████████████████████████| 9.51G/9.51G [00:20<00:00, 465MB/s]
Downloading (…)l-00005-of-00009.bin: 100%|████████████████████████████████████████████████████████████████████████████████| 9.51G/9.51G [00:19<00:00, 489MB/s]
Downloading (…)l-00006-of-00009.bin: 100%|████████████████████████████████████████████████████████████████████████████████| 9.51G/9.51G [00:20<00:00, 461MB/s]
Downloading (…)l-00007-of-00009.bin: 100%|████████████████████████████████████████████████████████████████████████████████| 9.51G/9.51G [00:19<00:00, 477MB/s]
Downloading (…)l-00008-of-00009.bin: 100%|████████████████████████████████████████████████████████████████████████████████| 9.51G/9.51G [00:19<00:00, 494MB/s]
Downloading (…)l-00009-of-00009.bin: 100%|████████████████████████████████████████████████████████████████████████████████| 7.58G/7.58G [00:16<00:00, 472MB/s]
Downloading shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [02:57<00:00, 19.72s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:31<00:00,  3.46s/it]
Downloading (…)neration_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 34.7kB/s]
Downloading (…)okenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████| 220/220 [00:00<00:00, 134kB/s]
Downloading (…)/main/tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████| 2.73M/2.73M [00:01<00:00, 2.07MB/s]
Downloading (…)cial_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████| 281/281 [00:00<00:00, 169kB/s]
Traceback (most recent call last):
  File "/opt/conda/bin/ct2-transformers-converter", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/ctranslate2/converters/transformers.py", line 1453, in main
    converter.convert_from_args(args)
  File "/opt/conda/lib/python3.7/site-packages/ctranslate2/converters/converter.py", line 54, in convert_from_args
    force=args.force,
  File "/opt/conda/lib/python3.7/site-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/opt/conda/lib/python3.7/site-packages/ctranslate2/converters/transformers.py", line 118, in _load
    spec = loader(model, tokenizer)
  File "/opt/conda/lib/python3.7/site-packages/ctranslate2/converters/transformers.py", line 172, in __call__
    spec = self.get_model_spec(model)
  File "/opt/conda/lib/python3.7/site-packages/ctranslate2/converters/transformers.py", line 1263, in get_model_spec
    multi_query_attention=model.config.multi_query,
  File "/opt/conda/lib/python3.7/site-packages/transformers/configuration_utils.py", line 261, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'RWConfig' object has no attribute 'multi_query'
```

Lib versions:
transformers==4.29.2
torch==1.13.1
ctranslate2==3.15.0

**Comment by michaelfeil** [comment]
FYI, Falcon 40B uses the 
config.json
```json
  "n_head_kv": 8,
```

instead this config from falcon 7B
```json
"multi_query": true,
```

**Comment by jgcb00** [comment]
So it's not possible to convert it ?
Is it plan to support the 40b models ?

Thanks

**Comment by guillaumekln** [comment]
I did not try the 40B version as I expected it would use the same configuration as 7B.

But it uses yet another definition of the multi-head attention that requires additional development...

**Comment by juliensalinas** [comment]
No worries @guillaumekln the 7B version is already working great, and to be honest today it is almost impossible to use the 40B version as it requires at least 96GB of VRAM. Since Ctranslate2 does not support multi-GPU I don't think it would be even possible to deploy this quantized model until GPUs with more than 80GB of VRAM are released.

So feel free to close this issue and thanks again for the great work 👍🏻

**Comment by guillaumekln** [comment]
With int8 quantization the 40B version should use about 40GB of memory.

**Comment by juliensalinas** [comment]
Oh true indeed!
So I would love to try that 😃

**Comment by silvacarl2** [comment]
if you need to borrow a server for anything let me know.

p.s. julien is a genius!

**Comment by juliensalinas** [comment]
Thx @guillaumekln , very much appreciated.
