### ISSUE TITLE
Support Tokenizers/AutoTokenizer remote code with trust_remote_code=True 

### ISSUE THREAD

**Issue by michaelfeil** [OpenNMT/CTranslate2#1334]
There are new models using the LLama-Architecture and OpenAI Tokenizer 

e.g. https://huggingface.co/Salesforce/codegen25-7b-multi, require the loading of tokenizer via trust_remote_code=True 
Therefore, the code crashes here:
https://github.com/OpenNMT/CTranslate2/blob/50ce6a76920e8eef15a47997353101348871ec3d/python/ctranslate2/converters/transformers.py#L136

**Comment by guillaumekln** [comment]
Do you want to send a PR for that? The code already has an attribute `trust_remote_code` that could be passed to the tokenizer loading.

**Comment by Shas3011** [comment]
Was facing the same issue, 

Made a PR that fixes this below is the link for it 

https://github.com/OpenNMT/CTranslate2/pull/1336

[Sorry not sure how to link the pr and the issue  ]

**Comment by wsxiaoys** [comment]
I patched with #1336 but still cannot convert codegen25-7b:

```
(base) ubuntu@ip-172-31-3-81:~/models/Codegen25-7B$ ct2-transformers-converter --model ./ --output_dir ctranslate2 --quantization=float16 --trust_remote_code
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:20<00:00,  6.73s/it]
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Using bos_token, but it is not set yet.
Using unk_token, but it is not set yet.
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/ct2-transformers-converter", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 1594, in main
    converter.convert_from_args(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 117, in _load
    spec = loader(model, tokenizer)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 174, in __call__
    tokens = self.get_vocabulary(model, tokenizer)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 183, in get_vocabulary
    tokenizer.get_vocab().items(), key=lambda item: item[1]
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/tokenization_codegen25.py", line 153, in get_vocab
    vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/tokenization_codegen25.py", line 153, in <dictcomp>
    vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/tokenization_codegen25.py", line 169, in _convert_id_to_token
    return self.encoder.decode_single_token_bytes(index).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 0: invalid start byte

```

**Comment by Shas3011** [comment]
That's an problem with the custom tokeniser code on Salesforce part not on ctranslate2 

Pr 1336 fixes the problem of ctranslate2 not importing custom tokeniser 

However there is still a bug with the tokenizer code shared by Salesforce team mainly the get_vocab method has not been properly implemented 

So we can only wait for a fix on that

**Comment by guillaumekln** [comment]
Closing this issue since the related PR has been merged.

A new version should be released in the coming days.
