### ISSUE TITLE
Unable to convert codegen25-7b-instruct

### ISSUE THREAD

**Issue by nenkoru** [OpenNMT/CTranslate2#1356]
Pretty much in the title.

```
ct2-transformers-converter --model Salesforce/codegen25-7b-instruct --revision main --quantization int8 --output_dir codegen25_ct2_int8 --trust_remote_code
```

```
Traceback (most recent call last):
  File "/home/nenkoru/miniconda3/envs/starcoder/bin/ct2-transformers-converter", line 8, in <module>
    sys.exit(main())
  File "/home/nenkoru/miniconda3/envs/starcoder/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 1593, in main
    converter.convert_from_args(args)
  File "/home/nenkoru/miniconda3/envs/starcoder/lib/python3.10/site-packages/ctranslate2/converters/converter.py", line 57, in convert_from_args
    return self.convert(
  File "/home/nenkoru/miniconda3/envs/starcoder/lib/python3.10/site-packages/ctranslate2/converters/converter.py", line 96, in convert
    model_spec = self._load()
  File "/home/nenkoru/miniconda3/envs/starcoder/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 125, in _load
    spec = loader(model, tokenizer)
  File "/home/nenkoru/miniconda3/envs/starcoder/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 180, in __call__
    tokens = self.get_vocabulary(model, tokenizer)
  File "/home/nenkoru/miniconda3/envs/starcoder/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 189, in get_vocabulary
    tokenizer.get_vocab().items(), key=lambda item: item[1]
  File "/home/nenkoru/.cache/huggingface/modules/transformers_modules/Salesforce/codegen25-7b-instruct/f6767817933d30454777dff1c2c7dc32c1e386cc/tokenization_codegen25.py", line 153, in get_vocab
    vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
  File "/home/nenkoru/.cache/huggingface/modules/transformers_modules/Salesforce/codegen25-7b-instruct/f6767817933d30454777dff1c2c7dc32c1e386cc/tokenization_codegen25.py", line 153, in <dictcomp>
    vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
  File "/home/nenkoru/.cache/huggingface/modules/transformers_modules/Salesforce/codegen25-7b-instruct/f6767817933d30454777dff1c2c7dc32c1e386cc/tokenization_codegen25.py", line 169, in _convert_id_to_token
    return self.encoder.decode_single_token_bytes(index).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 0: invalid start byte
```

```
pip3 show ctranslate2
Name: ctranslate2
Version: 3.17.0
```
```
pip3 show torch
Name: torch
Version: 2.1.0.dev20230709+cu121
```
```
pip3 show transformers
Name: transformers
Version: 4.30.2
```

**Comment by nenkoru** [comment]
Okay, I tried to do `errors='replace'` and it didn't work out.

```

**Comment by nenkoru** [comment]
> The initial error is coming from the tokenizer itself, not CTranslate2:
> 
> ```python
> >>> import transformers
> >>> tokenizer = transformers.AutoTokenizer.from_pretrained("Salesforce/codegen25-7b-instruct", trust_remote_code=True)
> >>> tokenizer.get_vocab()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/klein/.cache/huggingface/modules/transformers_modules/Salesforce/codegen25-7b-instruct/f6767817933d30454777dff1c2c7dc32c1e386cc/tokenization_codegen25.py", line 153, in get_vocab
>     vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
>   File "/home/klein/.cache/huggingface/modules/transformers_modules/Salesforce/codegen25-7b-instruct/f6767817933d30454777dff1c2c7dc32c1e386cc/tokenization_codegen25.py", line 153, in <dictcomp>
>     vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
>   File "/home/klein/.cache/huggingface/modules/transformers_modules/Salesforce/codegen25-7b-instruct/f6767817933d30454777dff1c2c7dc32c1e386cc/tokenization_codegen25.py", line 169, in _convert_id_to_token
>     return self.encoder.decode_single_token_bytes(index).decode("utf-8")
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 0: invalid start byte
> ```
> 
> Using `errors='replace'` is not a correct workaround since multiple tokens could be mapped to the same string. You can try using `errors='backslashreplace'` instead.
> 
> You might also want to contact the authors of this model to fix the tokenizer.

Yep, currently looking through the custom tokenizer that comes with this model and tiktoken.
Will update this issue.

**Comment by guillaumekln** [comment]
> Tried to load the model, and this is happening.

I think it's because the tokenizer does not define the properties `bos_token` and `unk_token`, unlike the Llama tokenizer. You can manually edit the file `config.json` in the converted model directory and set these fields to `"<|endoftext|>"` for example.

**Comment by nenkoru** [comment]
> > Tried to load the model, and this is happening.
> 
> I think it's because the tokenizer does not define the properties `bos_token` and `unk_token`, unlike the Llama tokenizer. You can manually edit the file `config.json` in the converted model directory and set these fields to `"<|endoftext|>"` for example.

Okay, I think issue could be closed. Will make appropriate PR into the tokenizer of this model.
