### ISSUE TITLE
Conversion of models does not work with torch <=1.12.1

### ISSUE THREAD

**Issue by RistoAle97** [OpenNMT/CTranslate2#1381]
Hi, I tried to convert a marian model following this [guide](https://opennmt.net/CTranslate2/guides/transformers.html) by using the command
```bash
ct2-transformers-converter --model Helsinki-NLP/opus-mt-en-fr --output_dir opus-mt-en-fr
```

and i got this error:
```
Traceback (most recent call last):
  File "/home/a.ristori/anaconda3/envs/MasterDegreeThesis/bin/ct2-transformers-converter", line 8, in <module>
    sys.exit(main())
  File "/home/a.ristori/anaconda3/envs/MasterDegreeThesis/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 1610, in main
    converter.convert_from_args(args)
  File "/home/a.ristori/anaconda3/envs/MasterDegreeThesis/lib/python3.10/site-packages/ctranslate2/converters/converter.py", line 57, in convert_from_args
    return self.convert(
  File "/home/a.ristori/anaconda3/envs/MasterDegreeThesis/lib/python3.10/site-packages/ctranslate2/converters/converter.py", line 96, in convert
    model_spec = self._load()
  File "/home/a.ristori/anaconda3/envs/MasterDegreeThesis/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 125, in _load
    spec = loader(model, tokenizer)
  File "/home/a.ristori/anaconda3/envs/MasterDegreeThesis/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 177, in __call__
    spec = self.get_model_spec(model)
  File "/home/a.ristori/anaconda3/envs/MasterDegreeThesis/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 354, in get_model_spec
    spec = super().get_model_spec(model)
  File "/home/a.ristori/anaconda3/envs/MasterDegreeThesis/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 240, in get_model_spec
    self.set_encoder(spec.encoder, model.model.encoder)
  File "/home/a.ristori/anaconda3/envs/MasterDegreeThesis/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 272, in set_encoder
    self.set_attention(
  File "/home/a.ristori/anaconda3/envs/MasterDegreeThesis/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 322, in set_attention
    utils.fuse_linear(spec.linear[0], split_layers)
  File "/home/a.ristori/anaconda3/envs/MasterDegreeThesis/lib/python3.10/site-packages/ctranslate2/converters/utils.py", line 13, in fuse_linear
    spec.weight = np_api.concatenate([layer.weight for layer in layers])
AttributeError: module 'torch' has no attribute 'concatenate'
```

`torch.concatenate` is an alias to `torch.cat`  and was introduced in torch 1.13 (ctrl+f "concatenate" on https://pytorch.org/docs/1.12/torch.html shows no method with such name) so it won't work with any previous version.

My suggestion is to make changes to the following function inside `python/ctranslate2/converters/utils.py`
```python
def fuse_linear(spec, layers):
    if not layers:
        raise ValueError("Cannot fuse linear layers: at least one layer is required")

    if isinstance(layers[0].weight, np.ndarray):
        np_api = np
    else:
        import torch as np_api

    spec.weight = np_api.concatenate([layer.weight for layer in layers])

    bias_dtype = None
    for layer in layers:
        if layer.has_bias():
            bias_dtype = layer.bias.dtype
            break

    if bias_dtype is not None:
        spec.bias = np_api.concatenate(
            [
                layer.bias
                if layer.has_bias()
                else np_api.zeros([layer.weight.shape[0]], dtype=bias_dtype)
                for layer in layers
            ]
        )
```
with
```python
def fuse_linear(spec, layers):
    if not layers:
        raise ValueError("Cannot fuse linear layers: at least one layer is required")

    if isinstance(layers[0].weight, np.ndarray):
        np_api = np
        f_concat = np_api.concatenate
    else:
        import torch as np_api
        f_concat = np_api.cat

    spec.weight = f_concat([layer.weight for layer in layers])

    bias_dtype = None
    for layer in layers:
        if layer.has_bias():
            bias_dtype = layer.bias.dtype
            break

    if bias_dtype is not None:
        spec.bias = f_concat(
            [
                layer.bias
                if layer.has_bias()
                else np_api.zeros([layer.weight.shape[0]], dtype=bias_dtype)
                for layer in layers
            ]
        )
```
in order to solve the issue.

**Comment by guillaumekln** [comment]
Sure, can you send a PR with this change?

**Comment by RistoAle97** [comment]
@guillaumekln sure, I will deal with it as soon as I get back home.
