### ISSUE TITLE
OpenNMT-py model conversion failed because of KeyError

### ISSUE THREAD

**Issue by filips123** [OpenNMT/CTranslate2#158]
I'm trying to convert OpenNMT-py model to CTranslate2 format, but it fails because of KeyError. The model that I'm trying to convert is available [here](https://0x0.st/imzR.pt) (it is named `paracrawl.pt` but it was renamed during uploading).

---

When I try to run conversion:

```
ct2-opennmt-py-converter --model_path paracrawl.pt --model_spec TransformerBase --output_dir paracrawl
```

It fails with `KeyError`:

```
Traceback (most recent call last):
  File "/usr/local/bin/ct2-opennmt-py-converter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/ctranslate2/bin/opennmt_py_converter.py", line 11, in main
    converters.OpenNMTPyConverter(args.model_path).convert_from_args(args)
  File "/usr/local/lib/python3.8/site-packages/ctranslate2/converters/converter.py", line 35, in convert_from_args
    return self.convert(
  File "/usr/local/lib/python3.8/site-packages/ctranslate2/converters/converter.py", line 52, in convert
    src_vocab, tgt_vocab = self._load(model_spec)
  File "/usr/local/lib/python3.8/site-packages/ctranslate2/converters/opennmt_py.py", line 27, in _load
    set_transformer_spec(model_spec, variables)
  File "/usr/local/lib/python3.8/site-packages/ctranslate2/converters/opennmt_py.py", line 39, in set_transformer_spec
    set_transformer_encoder(spec.encoder, variables, relative=spec.with_relative_position)
  File "/usr/local/lib/python3.8/site-packages/ctranslate2/converters/opennmt_py.py", line 43, in set_transformer_encoder
    set_input_layers(spec, variables, "encoder", relative=relative)
  File "/usr/local/lib/python3.8/site-packages/ctranslate2/converters/opennmt_py.py", line 59, in set_input_layers
    set_position_encodings(
  File "/usr/local/lib/python3.8/site-packages/ctranslate2/converters/opennmt_py.py", line 136, in set_position_encodings
    spec.encodings = _get_variable(variables, "%s.pe" % scope).squeeze()
  File "/usr/local/lib/python3.8/site-packages/ctranslate2/converters/opennmt_py.py", line 141, in _get_variable
    return variables[name].numpy()
KeyError: 'encoder.embeddings.make_embedding.pe.pe'
```

---

I'm using Python 3.8 on my custom `python:buster` Docker image with theese Python packages installed:

```
Package              Version
-------------------- ----------
absl-py              0.9.0
cachetools           4.0.0
certifi              2019.11.28
chardet              3.0.4
click                7.1.1
ConfigArgParse       1.0
ctranslate2          1.8.0
Flask                1.1.1
future               0.18.2
google-auth          1.11.3
google-auth-oauthlib 0.4.1
grpcio               1.27.2
idna                 2.9
itsdangerous         1.1.0
Jinja2               2.11.1
Markdown             3.2.1
MarkupSafe           1.1.1
numpy                1.18.1
oauthlib             3.1.0
OpenNMT-py           1.0.2
pip                  19.3.1
protobuf             3.11.3
pyasn1               0.4.8
pyasn1-modules       0.2.8
pyonmttok            1.18.3
requests             2.23.0
requests-oauthlib    1.3.0
rsa                  4.0
setuptools           41.6.0
six                  1.14.0
tensorboard          2.1.1
torch                1.4.0
torchtext            0.4.0
tqdm                 4.30.0
urllib3              1.25.8
waitress             1.4.3
Werkzeug             1.0.0
wheel                0.33.6
```

**Comment by guillaumekln** [comment]
This looks like to be a RNN based model. However, CTranslate2 only supports Transformer models at the moment. See the list of supported architectures in the README: https://github.com/OpenNMT/CTranslate2#converting-models

**Comment by filips123** [comment]
How to create Transformer model? I trained it with `opennmt_train` command of OpenNMT-py but I didn't know it created RNN model.

```
onmt_train -data dataset/paracrawl -save_model model/paracrawl -gpu_rank 0
```

**Comment by guillaumekln** [comment]
See https://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-the-transformer-model

**Comment by filips123** [comment]
Are there any other ways to train Transformer model? Because it looks like Transformer training from your URL takes way longer than training RNN model.

**Comment by guillaumekln** [comment]
Transformer models have more parameters than the default RNN model you initially trained. This makes the training slower but this type of models can reach much higher translation quality. If training time is critical, you can always add more GPUs or use a GPU that supports mixed precision training.

Let me close this issue as the original error related to CTranslate2 have been explained. If you have more question related to OpenNMT-py, please open a topic on the [forum](https://forum.opennmt.net/) or directly on the OpenNMT-py GitHub repo. Thanks!

**Comment by filips123** [comment]
Ok, thanks for support!

**Comment by filips123** [comment]
Will RNN models be supported in the future? Should I open new issue about them?

**Comment by guillaumekln** [comment]
There is no plan for that at the moment. Most production grade models are Transformer models nowadays.

**Comment by PJ-Finlay** [comment]
I also had this issue but I'm pretty sure I trained a Transformer.
```
$ ct2-opennmt-py-converter --model_path averaged.pt --model_spec TransformerBase --output_dir exported
Traceback (most recent call last):
  File "/usr/local/bin/ct2-opennmt-py-converter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/bin/opennmt_py_converter.py", line 11, in main
    converters.OpenNMTPyConverter(args.model_path).convert_from_args(args)
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/converter.py", line 35, in convert_from_args
    return self.convert(
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/converter.py", line 52, in convert
    src_vocab, tgt_vocab = self._load(model_spec)
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/opennmt_py.py", line 27, in _load
    set_transformer_spec(model_spec, variables)
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/opennmt_py.py", line 39, in set_transformer_spec
    set_transformer_encoder(spec.encoder, variables, relative=spec.with_relative_position)
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/opennmt_py.py", line 43, in set_transformer_encoder
    set_input_layers(spec, variables, "encoder", relative=relative)
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/opennmt_py.py", line 59, in set_input_layers
    set_position_encodings(
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/opennmt_py.py", line 136, in set_position_encodings
    spec.encodings = _get_variable(variables, "%s.pe" % scope).squeeze()
  File "/usr/local/lib/python3.8/dist-packages/ctranslate2/converters/opennmt_py.py", line 141, in _get_variable
    return variables[name].numpy()
KeyError: 'encoder.embeddings.make_embedding.pe.pe'
```
In my `config.yml`:
```
# Model
encoder_type: transformer
decoder_type: transformer
```
I also averaged two models together:
```
OpenNMT-py/tools/average_models.py -m <model1> <modlel2> -o averaged.pt
```
[Full code](https://github.com/argosopentech/onmt-models/tree/2fbbb1113fce0f428bc3037f8be270d0a00c8a22)

**Comment by guillaumekln** [comment]
The [reference configuration](https://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-the-transformer-model) uses `position_encoding: true`, but I don't see it in your configuration.

**Comment by PJ-Finlay** [comment]
That worked thanks!
