### ISSUE TITLE
Failed to convert fine-tuned whisper large-v2 model

### ISSUE THREAD

**Issue by yaoandy107** [OpenNMT/CTranslate2#1612]
I'm going to fine-tune the Whisper large-v2 model with PEFT, but when trying to convert to ct2, I got the error below:
```
config.json: 100% 1.77k/1.77k [00:00<00:00, 9.65MB/s]
/usr/local/lib/python3.10/dist-packages/transformers/quantizers/auto.py:147: UserWarning: You passed `quantization_config` or equivalent parameters to `from_pretrained` but the model you're loading already has a `quantization_config` attribute. The `quantization_config` from the model will be prevail.
  warnings.warn(warning_msg)
`low_cpu_mem_usage` was None, now set to True since model is quantized.
model.safetensors: 100% 1.77G/1.77G [01:08<00:00, 26.0MB/s]
generation_config.json: 100% 4.29k/4.29k [00:00<00:00, 19.2MB/s]
tokenizer_config.json: 100% 283k/283k [00:00<00:00, 470kB/s]
vocab.json: 100% 1.04M/1.04M [00:00<00:00, 1.30MB/s]
merges.txt: 100% 494k/494k [00:00<00:00, 827kB/s]
normalizer.json: 100% 52.7k/52.7k [00:00<00:00, 118MB/s]
added_tokens.json: 100% 34.6k/34.6k [00:00<00:00, 176kB/s]
special_tokens_map.json: 100% 2.19k/2.19k [00:00<00:00, 11.7MB/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/usr/local/bin/ct2-transformers-converter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 2008, in main
    converter.convert_from_args(args)
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 141, in _load
    spec = loader(model, tokenizer)
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 193, in __call__
    spec = self.get_model_spec(model)
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 886, in get_model_spec
    self.set_encoder(spec.encoder, model.model.encoder)
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 958, in set_encoder
    super().set_encoder(spec, encoder)
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 288, in set_encoder
    self.set_attention(
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 338, in set_attention
    utils.fuse_linear(spec.linear[0], split_layers)
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/utils.py", line 26, in fuse_linear
    spec.bias = concatenate(
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument tensors in method wrapper_CUDA_cat)
```

This is the command:
```shell
ct2-transformers-converter --model {trained_model_repo} --output_dir {trained_model_name}-ct2 --copy_files tokenizer.json preprocessor_config.json --quantization float16
```

But when I fine-tune `small.en` instead of `large-v2` with the same code, then everything works well.

## Environment
CTranslate2 version: 3.24.0
Transformers version: main (git+https://github.com/huggingface/transformers@709dc43239c66318f6f3c23123700192adf4fc2b)

**Comment by yaoandy107** [comment]
Besides, when using fine-tuned Whisper large-v3, I got another error:
```
adapter_model.safetensors: 100% 63.0M/63.0M [00:02<00:00, 26.4MB/s]
tokenizer_config.json: 100% 283k/283k [00:00<00:00, 715kB/s]
vocab.json: 100% 1.04M/1.04M [00:00<00:00, 1.30MB/s]
tokenizer.json: 100% 2.48M/2.48M [00:00<00:00, 4.12MB/s]
merges.txt: 100% 494k/494k [00:00<00:00, 822kB/s]
normalizer.json: 100% 52.7k/52.7k [00:00<00:00, 267kB/s]
added_tokens.json: 100% 34.6k/34.6k [00:00<00:00, 68.6MB/s]
special_tokens_map.json: 100% 2.19k/2.19k [00:00<00:00, 8.40MB/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/usr/local/bin/ct2-transformers-converter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 2008, in main
    converter.convert_from_args(args)
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 141, in _load
    spec = loader(model, tokenizer)
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 193, in __call__
    spec = self.get_model_spec(model)
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 886, in get_model_spec
    self.set_encoder(spec.encoder, model.model.encoder)
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 958, in set_encoder
    super().set_encoder(spec, encoder)
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 288, in set_encoder
    self.set_attention(
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 333, in set_attention
    self.set_linear(split_layers[0], attention.q_proj)
  File "/usr/local/lib/python3.10/dist-packages/ctranslate2/converters/transformers.py", line 223, in set_linear
    if module.bias is not None:
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Linear' object has no attribute 'bias'
```

**Comment by yaoandy107** [comment]
The error disappears when running the converter in a new Colab notebook without installing any additional libraries. Therefore, I'm closing this issue.
