### ISSUE TITLE
System error while converting Aya101

### ISSUE THREAD

**Issue by msharara1998** [OpenNMT/CTranslate2#1634]
I want to ctranslate Aya101 Cohere model, I ran this command:

`ct2-transformers-converter --model CohereForAI/aya-101  --output_dir ./models/ct2`

after model downloading I got this:

```Traceback (most recent call last):
  File "/home/aiadmin/miniconda3/envs/aya101/bin/ct2-transformers-converter", line 8, in <module>
    sys.exit(main())
  File "/home/aiadmin/miniconda3/envs/aya101/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 2008, in main
    converter.convert_from_args(args)
  File "/home/aiadmin/miniconda3/envs/aya101/lib/python3.10/site-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/home/aiadmin/miniconda3/envs/aya101/lib/python3.10/site-packages/ctranslate2/converters/converter.py", line 104, in convert
    model_spec.save(output_dir)
  File "/home/aiadmin/miniconda3/envs/aya101/lib/python3.10/site-packages/ctranslate2/specs/model_spec.py", line 532, in save
    super().save(output_dir)
  File "/home/aiadmin/miniconda3/envs/aya101/lib/python3.10/site-packages/ctranslate2/specs/model_spec.py", line 353, in save
    self._serialize(os.path.join(output_dir, "model.bin"))
  File "/home/aiadmin/miniconda3/envs/aya101/lib/python3.10/site-packages/ctranslate2/specs/model_spec.py", line 393, in _serialize
    model.write(value.to_bytes())
  File "/home/aiadmin/miniconda3/envs/aya101/lib/python3.10/site-packages/ctranslate2/specs/model_spec.py", line 730, in to_bytes
    return ctypes.string_at(self.tensor.data_ptr(), self.num_bytes())
  File "/home/aiadmin/miniconda3/envs/aya101/lib/python3.10/ctypes/__init__.py", line 517, in string_at
    return _string_at(ptr, size)
SystemError: Negative size passed to PyBytes_FromStringAndSize```

**Comment by msharara1998** [comment]
I've attempted to install the new version that you updated, via isntallation from source file as mentioned in documentation (pypi still hosting the older version which is before your fix so cant install via pip unless I am missing something). That being said, when I run `cmake ..` I get the following error:

```
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Build spdlog: 1.10.0
-- Build type: Release
-- Compiling for multiple CPU ISA and enabling runtime dispatch
-- Using OpenMP: /usr/lib/x86_64-linux-gnu/libiomp5.so
CMake Error at CMakeLists.txt:307 (message):
  MKL include directory not found
```

I made sure that mkl is installed.

**Comment by minhthuc2502** [comment]
Try to install:
```
wget -q https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB && \
    apt-key add *.PUB && \
    rm *.PUB && \
    echo "deb https://apt.repos.intel.com/oneapi all main" > /etc/apt/sources.list.d/oneAPI.list && \
    apt-get update && \
    apt-get install -y intel-oneapi-mkl-devel-$ONEAPI_VERSION
```

**Comment by msharara1998** [comment]
Okay, got you. It seems that I was missing some dependencies (anyway I need them for performance) like BLAS, oneDNN, and cuDNN, and MKL. Cmake worked when I installed them as standalone installation not via pip or conda.
Besides, I didnt know that I can convert directly, I will check it.
Thanks!
