### ISSUE TITLE
Build Ctranslate2 for android

### ISSUE THREAD

**Issue by glory03023** [OpenNMT/CTranslate2#1683]
Hello, everyone.
I am trying to use ctranslate2 on android device.
Hope any ctranslate2 expert to guide on how to use ctranslate2 on android.
maybe we need to cross-compile ctranslate2 for arm.
But it seems there is no way for android build in this project.
Thank you.

**Comment by Manamama** [comment]
Can be done. Follow the instructions. Change a lot in CmakeList.txt first to NONE.

**Comment by Jank14** [comment]
@glory03023 were u able to use ctranslate2 on android. I want to use my nmt models on android and host them there.Just wanted to know did it work for you and if so what steps did u follow? Thanks in advance

**Comment by Manamama** [comment]
It used to be more complicated (see my advice above). 

Now, I have just retried it, force reinstall:
```
Environment at system:
Linux localhost 4.14.186+ #1 SMP PREEMPT Thu Mar 17 16:28:22 CST 2022 aarch64 Android


PATH: /data/data/com.termux/files/usr/google-cloud-sdk/bin:/data/data/com.termux/files/home/.opam/default/bin:/data/data/com.termux/files/usr/bin:/system/bin/:/data/data/com.termux/files/usr/bin:/system/bin/:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/home/.local/bin

LD_PRELOAD: 

LD_LIBRARY_PATH: /data/data/com.termux/files/home/.local/lib:

CC: clang
CXX: clang++
C_INCLUDE_PATH: /data/data/com.termux/files/usr/lib/qt/mkspecs/common/uikit/:/data/data/com.termux/files/usr/include/epoxy/
FC: gfortran
CFLAGS: 
CXXFLAGS: 
LDFLAGS: -lm -lpython3.11 -llog
CPPFLAGS: 

ANDROID_NDK: /storage/7B27-F244/Installs/Android_ndk_sdk/android-ndk-r26b
```
and the simplest :
```
~/downloads $ git clone https://github.com/OpenNMT/CTranslate2/
Cloning into 'CTranslate2'...
remote: Enumerating objects: 23075, done.
remote: Counting objects: 100% (4226/4226), done.
remote: Compressing objects: 100% (636/636), done.
remote: Total 23075 (delta 3823), reused 3746 (delta 3587), pack-reused 18849
Receiving objects: 100% (23075/23075), 13.91 MiB | 1.94 MiB/s, done.
Resolving deltas: 100% (17231/17231), done.
[1]+  Done                    updatedb  (wd: ~)
(wd now: ~/downloads)
~/downloads $ cd CTranslate2/
~/downloads/CTranslate2 $ ls
 CHANGELOG.md   cli   cmake   CMakeLists.txt   CONTRIBUTING.md   docker   docs   examples   include   LICENSE   python   README.md  󱧼 src  󰙨 tests   third_party   tools
~/downloads/CTranslate2 $ pip install ./python/ -v
Using pip 24.2 from /data/data/com.termux/files/usr/lib/python3.11/site-packages/pip (python 3.11)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
Processing ./python
  Running command python setup.py egg_info
  running egg_info
... 
 changing mode of /data/data/com.termux/files/usr/bin/ct2-fairseq-converter to 755
  changing mode of /data/data/com.termux/files/usr/bin/ct2-marian-converter to 755
  changing mode of /data/data/com.termux/files/usr/bin/ct2-openai-gpt2-converter to 755
  changing mode of /data/data/com.termux/files/usr/bin/ct2-opennmt-py-converter to 755
  changing mode of /data/data/com.termux/files/usr/bin/ct2-opennmt-tf-converter to 755
  changing mode of /data/data/com.termux/files/usr/bin/ct2-opus-mt-converter to 755
  changing mode of /data/data/com.termux/files/usr/bin/ct2-transformers-converter to 755
Successfully installed ctranslate2-4.3.1
~/downloads/CTranslate2 $ 


```
resulting (on my system at least) with :

```
~ $ pip show ctranslate2
Name: ctranslate2
Version: 4.3.1
Summary: Fast inference engine for Transformer models
Home-page: https://opennmt.net
Author: OpenNMT
Author-email: 
License: MIT
Location: /data/data/com.termux/files/usr/lib/python3.11/site-packages
Requires: numpy, pyyaml, setuptools
Required-by: faster-whisper
~ $ 
```

**Comment by ranjitsingha** [comment]
> It used to be more complicated (see my advice above).
> 
> Now, I have just retried it, force reinstall:
> 
> ```
> Environment at system:
> Linux localhost 4.14.186+ #1 SMP PREEMPT Thu Mar 17 16:28:22 CST 2022 aarch64 Android
> 
> 
> PATH: /data/data/com.termux/files/usr/google-cloud-sdk/bin:/data/data/com.termux/files/home/.opam/default/bin:/data/data/com.termux/files/usr/bin:/system/bin/:/data/data/com.termux/files/usr/bin:/system/bin/:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/home/.local/bin
> 
> LD_PRELOAD: 
> 
> LD_LIBRARY_PATH: /data/data/com.termux/files/home/.local/lib:
> 
> CC: clang
> CXX: clang++
> C_INCLUDE_PATH: /data/data/com.termux/files/usr/lib/qt/mkspecs/common/uikit/:/data/data/com.termux/files/usr/include/epoxy/
> FC: gfortran
> CFLAGS: 
> CXXFLAGS: 
> LDFLAGS: -lm -lpython3.11 -llog
> CPPFLAGS: 
> 
> ANDROID_NDK: /storage/7B27-F244/Installs/Android_ndk_sdk/android-ndk-r26b
> python2-numpy/tur-packages 1.16.6-1 aarch64
> 
> ~ $ pip show numpy
> Name: numpy
> Version: 1.26.5
> ```
> 
> and the simplest :
> 
> ```
> pip install pybind11
> 
> 
> ~/downloads $ git clone https://github.com/OpenNMT/CTranslate2/
> Cloning into 'CTranslate2'...
> remote: Enumerating objects: 23075, done.
> remote: Counting objects: 100% (4226/4226), done.
> remote: Compressing objects: 100% (636/636), done.
> remote: Total 23075 (delta 3823), reused 3746 (delta 3587), pack-reused 18849
> Receiving objects: 100% (23075/23075), 13.91 MiB | 1.94 MiB/s, done.
> Resolving deltas: 100% (17231/17231), done.
> [1]+  Done                    updatedb  (wd: ~)
> (wd now: ~/downloads)
> ~/downloads $ cd CTranslate2/
> ~/downloads/CTranslate2 $ ls
>  CHANGELOG.md   cli   cmake   CMakeLists.txt   CONTRIBUTING.md   docker   docs   examples   include   LICENSE   python   README.md  󱧼 src  󰙨 tests   third_party   tools
> 
> #is not pulled automatically alas:
> cd third_party
> git clone https://github.com/jarro2783/cxxopts
> cd ..
> 
> ~/downloads/CTranslate2 $ pip install ./python/ -v
> Using pip 24.2 from /data/data/com.termux/files/usr/lib/python3.11/site-packages/pip (python 3.11)
> Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
> Processing ./python
>   Running command python setup.py egg_info
>   running egg_info
> ... 
>  changing mode of /data/data/com.termux/files/usr/bin/ct2-fairseq-converter to 755
>   changing mode of /data/data/com.termux/files/usr/bin/ct2-marian-converter to 755
>   changing mode of /data/data/com.termux/files/usr/bin/ct2-openai-gpt2-converter to 755
>   changing mode of /data/data/com.termux/files/usr/bin/ct2-opennmt-py-converter to 755
>   changing mode of /data/data/com.termux/files/usr/bin/ct2-opennmt-tf-converter to 755
>   changing mode of /data/data/com.termux/files/usr/bin/ct2-opus-mt-converter to 755
>   changing mode of /data/data/com.termux/files/usr/bin/ct2-transformers-converter to 755
> Successfully installed ctranslate2-4.3.1
> ~/downloads/CTranslate2 $ 
> ```
> 
> resulting (on my system at least) in :
> 
> ```
> ~ $ pip show ctranslate2
> Name: ctranslate2
> Version: 4.3.1
> Summary: Fast inference engine for Transformer models
> Home-page: https://opennmt.net
> Author: OpenNMT
> Author-email: 
> License: MIT
> Location: /data/data/com.termux/files/usr/lib/python3.11/site-packages
> Requires: numpy, pyyaml, setuptools
> Required-by: faster-whisper
> ~ $ 
> ```

Since you have successfully installed CTranslate2 in termux. is it possible to share me the .whl or wheel file to me

**Comment by Manamama** [comment]
Note to self, as I always forget how I had done it: 

```
git submodule update --init --recursive
cd build
cmake .. -DOPENMP_RUNTIME=COMP -DWITH_OPENBLAS=ON -DWITH_MKL=OFF  -DOPENBLAS_INCLUDE_DIR=/data/data/com.termux/files/usr/include/openblas -DCMAKE_POLICY_VERSION_MINIMUM=3.5
make install
```
and later the Python stuff  from the root folder:
```
cd python
pip install -v . -U
```
 
- all that assuming that :
```
apt list | grep openblas

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

blas-openblas/stable,now 0.3.29 aarch64 [installed]
libopenblas-static/stable 0.3.29 aarch64
libopenblas/stable,now 0.3.29 aarch64 [installed]
openblas-static/termux 0.3.7 aarch64
openblas/tur-packages 0.3.21-1 aarch64

```
etc. 



Update: `-DCMAKE_POLICY_VERSION_MINIMUM=3.5` is also needed, as without it: 

```
~/.../CTranslate2/build $ cmake .. -DWITH_OPENBLAS=ON -DWITH_RUY=ON -DWITH_MKL=OFF -DWITH_DNNL=OFF -DOPENMP_RUNTIME=COMP   -DCMAKE_INSTALL_PREFIX=$PREFIX  -DOPENBLAS_INCLUDE_DIR=/data/data/com.termux/files/usr/include/openblas
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- Compiler Id: Clang
-- Compiler Version: 21.1.8
-- Build spdlog: 1.10.0
-- Build type: RelWithDebInfo
-- Compiling for multiple CPU ISA and enabling runtime dispatch
-- Using OpenMP: /data/data/com.termux/files/usr/lib/libomp.a
-- Found OpenBLAS include directory: /data/data/com.termux/files/usr/include/openblas
-- Found OpenBLAS library: /data/data/com.termux/files/usr/lib/libopenblas.so
CMake Deprecation Warning at third_party/ruy/third_party/cpuinfo/CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
CMake Error at third_party/ruy/third_party/cpuinfo/deps/clog/CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 3.5 has been removed from CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.


-- Configuring incomplete, errors occurred!
```

**Comment by Benjamin-Loison** [comment]
<details>
<summary>Old message:</summary>

@Manamama 

Do you succeed running `from ctranslate2 import Translator`?

On my x86-64 LineageOS 23.0 virtual machine:

```bash
python3 -c 'from ctranslate2 import Translator'
```
<details>
<summary>Output:</summary>

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'Translator' from 'ctranslate2' (/data/data/com.termux/files/home/CTranslate2/python/ctranslate2/__init__.py)
```
</details>

My aim is to run up-to-date argos-translate, see [argosopentech/argos-translate/issues/317](https://github.com/argosopentech/argos-translate/issues/317).

Personal notes: [Benjamin_Loison/PyQt5/issues/1#issuecomment-11149310](https://codeberg.org/Benjamin_Loison/PyQt5/issues/1#issuecomment-11149310)
</details>

For reference, if you face:

```bash
python3 -c 'from ctranslate2 import Translator'
```
<details>
<summary>Output:</summary>

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'Translator' from 'ctranslate2' (/data/data/com.termux/files/home/CTranslate2/python/ctranslate2/__init__.py)
```
</details>

then just `cd` to solve the issue.

**Comment by Manamama** [comment]
Re: https://github.com/OpenNMT/CTranslate2/issues/1683#issuecomment-3987531819 - you mean on my Droid? 

It had been working for over 2 years with `whisperx` and such until the recent update to Python3.13, where I had to reinstall the lot. 

Very freshly reinstalled and what you ask about does work: 

```
~ $ ipython 
Python 3.13.12 (main, Mar  5 2026, 05:03:04) [Clang 21.0.0 (https://android.googlesource.com/toolchain/llvm-project 5e96669f0
Type 'copyright', 'credits' or 'license' for more information
IPython 9.10.0 -- An enhanced Interactive Python. Type '?' for help.
Tip: You can use `%hist` to view history, see the options with `%history?`

In [1]: from ctranslate2 import Translator
/data/data/com.termux/files/usr/lib/python3.13/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.0.0)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(

In [2]:                                                                                                                                                                                       
Do you really want to exit ([y]/n)? y
~ $ pip show ctranslate2
Name: ctranslate2
Version: 4.7.1
Summary: Fast inference engine for Transformer models
Home-page: https://opennmt.net
Author: OpenNMT
Author-email: 
License: MIT
Location: /data/data/com.termux/files/usr/lib/python3.13/site-packages
Requires: numpy, pyyaml, setuptools
Required-by: 
~ $ 
```
but I have not tested it with: `Required-by: faster-whisper, whisperx` as I am still struggling with https://github.com/scipy/scipy/issues/24744#issuecomment-4004674959 , which installs but for now my Gemini AI is struggling with some finer details thereof as: `../sklearn/meson.build:39:18: ERROR: Command `/data/data/com.termux/files/usr/bin/python3.13 -c 'import scipy; print(scipy.__version__)'` failed with status 1 ` and such.

**Comment by Benjamin-Loison** [comment]
[#issuecomment-4005871779](#issuecomment-4005871779) Yes I was referring to your Android, but as I specified *Old message*, my question is no more relevant as I ended up solving my issue, thank you anyway.
