### ISSUE TITLE
Trouble converting Mistral-Nemo despite architecture indicating MistralForCausalLM

### ISSUE THREAD

**Issue by BBC-Esq** [OpenNMT/CTranslate2#1743]
Has anyone had luck converting the model located here:

https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407

I haven't.  I've even tried renaming the ```consolidated.safetensors``` file to ```model.safetensors``` just to be safe, but no dice.  I'm wondering if despite the architecture being Mistral, there's some kind of nuance that ```Ctranslate2``` didn't take account of.  I noticed that the HF Repo indicates that only the development version of Transformers supports it, not the latest PyPi release so...this lends credibility to my hypothesis but I'm no expert.

Thanks!

**Comment by vince62s** [comment]
the only difference is head_dim being 128 which is NOT hidden dim // n_heads

**Comment by BBC-Esq** [comment]
Hmm...so would that necessitate altering the Mistral converter or any idea why my conversion script wouldn't work?  Here's what I'm using...

```
from PySide6.QtWidgets import QApplication, QWidget, QPushButton, QLabel, QFileDialog, QMessageBox, QVBoxLayout, QHBoxLayout, QCheckBox, QTextEdit, QStyleFactory
from PySide6.QtCore import QThread, Signal
import subprocess
import os

class ConversionThread(QThread):
    started = Signal(str, str)
    finished = Signal(str, str)
    error = Signal(str)

    def __init__(self, command, quantization):
        super().__init__()
        self.command = command
        self.quantization = quantization

    def run(self):
        self.started.emit(self.quantization, self.command)
        result = subprocess.run(self.command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if result.returncode == 0:
            self.finished.emit(self.quantization, result.stdout)
        else:
            self.error.emit(f"Command failed with return code {result.returncode}: {result.stderr}")

class App(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("chintellalaw.com - for non-commercial use")
        self.model_path = ""
        self.resize(800, 500)
        layout = QVBoxLayout(self)

        browse_layout = QHBoxLayout()
        self.browse_btn = QPushButton("Browse")
        self.browse_btn.clicked.connect(self.browse)
        browse_layout.addWidget(self.browse_btn)

        self.path_label = QLabel("")
        browse_layout.addWidget(self.path_label)
        layout.addLayout(browse_layout)

        self.quantization_options = ["float32", "float16", "bfloat16", "int8_float32", "int8_float16", "int8_bfloat16", "int8"]
        self.quant_vars = {option: QCheckBox(option) for option in self.quantization_options}

        quant_layout = QHBoxLayout()
        for option, chk in self.quant_vars.items():
            chk.setChecked(False)
            quant_layout.addWidget(chk)
        layout.addLayout(quant_layout)

        self.run_btn = QPushButton("Run")
        self.run_btn.clicked.connect(self.run_conversion)
        layout.addWidget(self.run_btn)

        self.output_text = QTextEdit()
        self.output_text.setReadOnly(True)
        layout.addWidget(self.output_text)

        self.conversion_queue = []
        self.current_conversion = None

    def browse(self):
        path = QFileDialog.getExistingDirectory(self, "Select Model Directory")
        if path:
            self.model_path = path
            self.path_label.setText(path)

    def append_to_text_widget(self, content):
        self.output_text.append(content)

    def run_conversion(self):
        self.output_text.clear()
        self.conversion_queue.clear()
        if not self.model_path:
            QMessageBox.critical(self, "Error", "Please select a model directory.")
            return

        for option, chk in self.quant_vars.items():
            if chk.isChecked():
                self.conversion_queue.append(option)
        self.process_next_conversion()

    def process_next_conversion(self):
        if self.conversion_queue:
            option = self.conversion_queue.pop(0)
            model_dir = self.model_path
            output_dir = os.path.join(os.path.dirname(model_dir), f'{os.path.basename(model_dir)}-ct2-{option}')
            copy_files = [filename for filename in os.listdir(model_dir) if not filename.endswith(('.bin', '.safetensors', 'onnx')) and filename not in ["config.json", ".git", "coreml", "configs", "runs", ".idea"]]
            if copy_files:
                copy_files_option = ' '.join([f'"{filename}"' for filename in copy_files])
                copy_files_cmd_part = f'--copy_files {copy_files_option} '
            else:
                copy_files_cmd_part = ''
            cmd = (f'ct2-transformers-converter --model "{model_dir}" '
                   f'--output_dir "{output_dir}" '
                   f'--quantization {option} '
                   f'--low_cpu_mem_usage '
                   f'--trust_remote_code '
                   f'{copy_files_cmd_part.strip()}')
            self.current_conversion = ConversionThread(cmd, option)
            self.current_conversion.started.connect(self.on_conversion_started)
            self.current_conversion.finished.connect(self.on_conversion_finished)
            self.current_conversion.error.connect(self.on_conversion_error)
            self.current_conversion.start()
        else:
            self.append_to_text_widget("All selected conversions are complete.")

    def on_conversion_started(self, quantization, command):
        self.append_to_text_widget(f"Starting conversion for {quantization} with command:\n{command}")

    def on_conversion_finished(self, quantization, output):
        completion_message = f"Conversion completed for {quantization}.\n{output}"
        self.append_to_text_widget(completion_message)
        self.process_next_conversion()

    def on_conversion_error(self, error_message):
        self.append_to_text_widget(error_message)

if __name__ == "__main__":
    app = QApplication([])
    app.setStyle(QStyleFactory.create("Fusion"))
    widget = App()
    widget.show()
    app.exec()
```

**Comment by BBC-Esq** [comment]
https://github.com/huggingface/transformers/pull/32050

**Comment by minhthuc2502** [comment]
Have to wait the transformers's release first. I tested the ct2 converter with transformers dev version, it finished successfully but not sure if it works fine due to some changes for example ``head_dim`` remarked by @vince62s.

**Comment by vince62s** [comment]
should be fine in fact
https://github.com/OpenNMT/CTranslate2/blob/master/python/ctranslate2/converters/transformers.py#L1329

**Comment by BBC-Esq** [comment]
> should be fine in fact https://github.com/OpenNMT/CTranslate2/blob/master/python/ctranslate2/converters/transformers.py#L1329

Not sure

**Comment by Theodotus1243** [comment]
For me this model succesfully converted and runned
[nvidia/Mistral-NeMo-Minitron-8B-Base](https://huggingface.co/nvidia/Mistral-NeMo-Minitron-8B-Base)

So everything should be fine

**Comment by BBC-Esq** [comment]
Any update on this?  I've tried again and I initially got an error saying it couldn't find a relevant .bin or .safetensors files...I noticed that the repo has consolidated.safetensors...so I renamed this large file to model.safetensors.  This resolved the first error, but now I'm getting this error:

```
ct2-transformers-converter --model "D:/Scripts/bench_chat/models/Mistral-Nemo-Instruct-2407" --output_dir "D:/Scripts/bench_chat/models\Mistral-Nemo-Instruct-2407-ct2-int8" --quantization int8 --low_cpu_mem_usage --trust_remote_code --copy_files "generation_config.json" "merges.txt" "params.json" "README.md" "special_tokens_map.json" "tekken.json" "tokenizer.json" "tokenizer_config.json" "vocab.json"
Command failed with return code 1: The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Scripts\bench_chat\Scripts\ct2-transformers-converter.exe\__main__.py", line 7, in <module>
  File "D:\Scripts\bench_chat\Lib\site-packages\ctranslate2\converters\transformers.py", line 2482, in main
    converter.convert_from_args(args)
  File "D:\Scripts\bench_chat\Lib\site-packages\ctranslate2\converters\converter.py", line 50, in convert_from_args
    return self.convert(
           ^^^^^^^^^^^^^
  File "D:\Scripts\bench_chat\Lib\site-packages\ctranslate2\converters\converter.py", line 89, in convert
    model_spec = self._load()
                 ^^^^^^^^^^^^
  File "D:\Scripts\bench_chat\Lib\site-packages\ctranslate2\converters\transformers.py", line 138, in _load
    model = self.load_model(model_class, self._model_name_or_path, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scripts\bench_chat\Lib\site-packages\ctranslate2\converters\transformers.py", line 163, in load_model
    return model_class.from_pretrained(model_name_or_path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scripts\bench_chat\Lib\site-packages\transformers\modeling_utils.py", line 3704, in from_pretrained
    if metadata.get("format") == "pt":
       ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by BBC-Esq** [comment]
Closing this issue.  Apparently, the repo files were updated to be compatible with HF shortly after I downloaded them a few months ago.  not sure if they will run correct, but the conversion is working now.
