### ISSUE TITLE
Failed to convert models from OpenNMT-py

### ISSUE THREAD

**Issue by huchinlp** [OpenNMT/CTranslate2#280]
Hi,

I installed OpenNMT-py and ctranslate2 with these commands:

`pip install --upgrade pip`
`pip install OpenNMT-py`
`pip install ctranslate2`

I can use the following command to translate the text:
`onmt_translate -model averaged-10-epoch.pt -src test.en -output pred.txt  -replace_unk --beam_size 1 --batch_size 64 -gpu 0`

But I got an error when running the converter:

`Traceback (most recent call last):
  File "/home/xxx/anaconda3/bin/ct2-opennmt-py-converter", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/anaconda3/lib/python3.6/site-packages/ctranslate2/bin/opennmt_py_converter.py", line 11, in main
    converters.OpenNMTPyConverter(args.model_path).convert_from_args(args)
  File "/home/xxx/anaconda3/lib/python3.6/site-packages/ctranslate2/converters/converter.py", line 40, in convert_from_args
    force=args.force)
  File "/home/xxx/anaconda3/lib/python3.6/site-packages/ctranslate2/converters/converter.py", line 52, in convert
    src_vocab, tgt_vocab = self._load(model_spec)
  File "/home/xxx/anaconda3/lib/python3.6/site-packages/ctranslate2/converters/opennmt_py.py", line 22, in _load
    checkpoint = torch.load(self._model_path, map_location="cpu")
  File "/home/xxx/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/xxx/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 765, in _legacy_load
    result = unpickler.load()
  File "/home/xxx/anaconda3/lib/python3.6/site-packages/torchtext/vocab.py", line 119, in __setstate__
    if state['unk_index'] is None:
KeyError: 'unk_index'`

**Comment by huchinlp** [comment]
It seems like the version of pytorch or torchtext is incorrect?

**Comment by guillaumekln** [comment]
See #109 and #160.

You should update `torchtext`.

**Comment by huchinlp** [comment]
> See #109 and #160.
> 
> You should update `torchtext`.

Thanks, it works after updating `torchtext`.
