### ISSUE TITLE
ct2-opennmt-tf-converter: vocabulary size error

### ISSUE THREAD

**Issue by ican24** [OpenNMT/CTranslate2#532]
Dear Team,

Each time I am facing vocabulary size error, when I am running ct2-opennmt-tf-converter.
It is not matter that the vocabulary is separate or share.
 
Is there any solution for my case?
The translation model was fully completed after 500k steps.
The inference is correctly working with the help of
onmt-main --config conf/data.yml --auto_config infer --features_file  test

Below is error output. 
```
(base) deep@deep-MS-7B51:/corpuses/worksmt/OpenNMT-tf$ ct2-opennmt-tf-converter --model_path run.hyen/ --model_type TransformerBase --output_dir ctranslate_model --src_vocab spm/share1.vocab --tgt_vocab spm/share1.vocab
2021-08-01 10:21:08.762010: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/home/deep/anaconda3/bin/ct2-opennmt-tf-converter", line 8, in <module>
    sys.exit(main())
  File "/home/deep/anaconda3/lib/python3.7/site-packages/ctranslate2/converters/opennmt_tf.py", line 360, in main
    ).convert_from_args(args)
  File "/home/deep/anaconda3/lib/python3.7/site-packages/ctranslate2/converters/converter.py", line 35, in convert_from_args
    force=args.force,
  File "/home/deep/anaconda3/lib/python3.7/site-packages/ctranslate2/converters/converter.py", line 53, in convert
    model_spec.validate()
  File "/home/deep/anaconda3/lib/python3.7/site-packages/ctranslate2/specs/model_spec.py", line 262, in validate
    "of size %d" % (name.capitalize(), len(vocabulary), expected_size)
ValueError: Source vocabulary has size 34752 but the model expected a vocabulary of size 35037
```
Thank you in advance!

**Comment by guillaumekln** [comment]
Can you try converting directly from OpenNMT-tf?

```bash
onmt-main --config conf/data.yml --auto_config export --export_format ctranslate2 --export_dir ctranslate_model
```

**Comment by ican24** [comment]
Thank you!
I used "export" method of onmt-main.
Now my case is solved. Actually I did not need to use sentencepiece for CTranslate2, because my training was done without this tokenization.
