### ISSUE TITLE
ImportError: DLL load failed while importing translator when trying to import ctranslate2 as a python module

### ISSUE THREAD

**Issue by AlHering** [OpenNMT/CTranslate2#551]
Hello and thank you for your time.
(Windows 10, Microsoft Visual Studio Code 2019, Intel oneAPI, Python 3.8.11, Anaconda (conda 4.9.2))

In order to use [ArgosTranslate](https://github.com/argosopentech/argos-translate) on Windows I need to build CTranslate2 from source. I could not find a workaround to get the module running on Windows. If there is an easier way, please let me know.

Building and installing the translate.exe seemed to have worked at first. Issueing 
`.\translate.exe -help` at least works as intended. However, other tries like
`echo "Hello World" | ."R:\ctranslate\bin\translate.exe" --model ende_ctranslate2/ --device auto "Hallo Welt"`
resulted in abort() calls (Debug Errors). 

At first I thought, building and installing the python module worked too:
```
R:\Ressourcen\Pakete\CTranslate2\python> python setup.py build
running build
running build_py
creating build\lib.win-amd64-3.8
creating build\lib.win-amd64-3.8\ctranslate2
copying ctranslate2\version.py -> build\lib.win-amd64-3.8\ctranslate2
copying ctranslate2\__init__.py -> build\lib.win-amd64-3.8\ctranslate2
creating build\lib.win-amd64-3.8\ctranslate2\converters
copying ctranslate2\converters\converter.py -> build\lib.win-amd64-3.8\ctranslate2\converters
copying ctranslate2\converters\fairseq.py -> build\lib.win-amd64-3.8\ctranslate2\converters
copying ctranslate2\converters\opennmt_py.py -> build\lib.win-amd64-3.8\ctranslate2\converters
copying ctranslate2\converters\opennmt_tf.py -> build\lib.win-amd64-3.8\ctranslate2\converters
copying ctranslate2\converters\utils.py -> build\lib.win-amd64-3.8\ctranslate2\converters
copying ctranslate2\converters\__init__.py -> build\lib.win-amd64-3.8\ctranslate2\converters
creating build\lib.win-amd64-3.8\ctranslate2\specs
copying ctranslate2\specs\attention_spec.py -> build\lib.win-amd64-3.8\ctranslate2\specs
copying ctranslate2\specs\common_spec.py -> build\lib.win-amd64-3.8\ctranslate2\specs
copying ctranslate2\specs\model_spec.py -> build\lib.win-amd64-3.8\ctranslate2\specs
copying ctranslate2\specs\transformer_spec.py -> build\lib.win-amd64-3.8\ctranslate2\specs
copying ctranslate2\specs\__init__.py -> build\lib.win-amd64-3.8\ctranslate2\specs
running build_ext
building 'ctranslate2.translator' extension
creating build\temp.win-amd64-3.8
creating build\temp.win-amd64-3.8\Release
R:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IR:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\lib\site-packages\pybind11\include" "-IR:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\include" "-IR:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\include" "-IR:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IR:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tptranslator.cc /Fobuild\temp.win-amd64-3.8\Release\translator.obj /std:c++17
translator.cc
translator.cc(63): warning C4996: 'std::_Arg_types<const std::string &>::argument_type': warning STL4007: Many result_type typedefs and all argument_type, first_argument_type, and second_argument_type typedefs are deprecated in C++17. You can define _SILENCE_CXX17_ADAPTOR_TYPEDEFS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
translator.cc(196): note: Siehe Verweis auf die gerade kompilierte Klasse Vorlage-Instanziierung "SafeCaller<TranslatorWrapper::TokenizeFn>".
translator.cc(63): warning C4996: 'std::_Arg_types<const std::vector<std::string,std::allocator<std::string>> &>::argument_type': warning STL4007: Many result_type typedefs and all argument_type, first_argument_type, and second_argument_type typedefs are deprecated in C++17. You can define _SILENCE_CXX17_ADAPTOR_TYPEDEFS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
translator.cc(198): note: Siehe Verweis auf die gerade kompilierte Klasse Vorlage-Instanziierung "SafeCaller<TranslatorWrapper::DetokenizeFn>".
R:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:R:\ctranslate\lib "/LIBPATH:R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\libs" "/LIBPATH:R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\PCbuild\amd64" "/LIBPATH:R:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:R:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" ctranslate2.lib /EXPORT:PyInit_translator build\temp.win-amd64-3.8\Release\translator.obj /OUT:build\lib.win-amd64-3.8\ctranslate2\translator.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\translator.cp38-win_amd64.lib
   Bibliothek "build\temp.win-amd64-3.8\Release\translator.cp38-win_amd64.lib" und Objekt "build\temp.win-amd64-3.8\Release\translator.cp38-win_amd64.exp" werden erstellt.
Code wird generiert.
Codegenerierung ist abgeschlossen.
```
```
(ProtocolPackages) PS R:\Ressourcen\Pakete\CTranslate2\python> python setup.py install
running install
running bdist_egg
running egg_info
writing ctranslate2.egg-info\PKG-INFO
writing dependency_links to ctranslate2.egg-info\dependency_links.txt
writing entry points to ctranslate2.egg-info\entry_points.txt
writing requirements to ctranslate2.egg-info\requires.txt
writing top-level names to ctranslate2.egg-info\top_level.txt
reading manifest file 'ctranslate2.egg-info\SOURCES.txt'
writing manifest file 'ctranslate2.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\ctranslate2
creating build\bdist.win-amd64\egg\ctranslate2\converters
copying build\lib.win-amd64-3.8\ctranslate2\converters\converter.py -> build\bdist.win-amd64\egg\ctranslate2\converters
copying build\lib.win-amd64-3.8\ctranslate2\converters\fairseq.py -> build\bdist.win-amd64\egg\ctranslate2\converters
copying build\lib.win-amd64-3.8\ctranslate2\converters\opennmt_py.py -> build\bdist.win-amd64\egg\ctranslate2\converters
copying build\lib.win-amd64-3.8\ctranslate2\converters\opennmt_tf.py -> build\bdist.win-amd64\egg\ctranslate2\converters
copying build\lib.win-amd64-3.8\ctranslate2\converters\utils.py -> build\bdist.win-amd64\egg\ctranslate2\converters
copying build\lib.win-amd64-3.8\ctranslate2\converters\__init__.py -> build\bdist.win-amd64\egg\ctranslate2\converters
creating build\bdist.win-amd64\egg\ctranslate2\specs
copying build\lib.win-amd64-3.8\ctranslate2\specs\attention_spec.py -> build\bdist.win-amd64\egg\ctranslate2\specs
copying build\lib.win-amd64-3.8\ctranslate2\specs\common_spec.py -> build\bdist.win-amd64\egg\ctranslate2\specs
copying build\lib.win-amd64-3.8\ctranslate2\specs\model_spec.py -> build\bdist.win-amd64\egg\ctranslate2\specs
copying build\lib.win-amd64-3.8\ctranslate2\specs\transformer_spec.py -> build\bdist.win-amd64\egg\ctranslate2\specs
copying build\lib.win-amd64-3.8\ctranslate2\specs\__init__.py -> build\bdist.win-amd64\egg\ctranslate2\specs
copying build\lib.win-amd64-3.8\ctranslate2\translator.cp38-win_amd64.pyd -> build\bdist.win-amd64\egg\ctranslate2
copying build\lib.win-amd64-3.8\ctranslate2\version.py -> build\bdist.win-amd64\egg\ctranslate2
copying build\lib.win-amd64-3.8\ctranslate2\__init__.py -> build\bdist.win-amd64\egg\ctranslate2
byte-compiling build\bdist.win-amd64\egg\ctranslate2\converters\converter.py to converter.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\ctranslate2\converters\fairseq.py to fairseq.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\ctranslate2\converters\opennmt_py.py to opennmt_py.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\ctranslate2\converters\opennmt_tf.py to opennmt_tf.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\ctranslate2\converters\utils.py to utils.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\ctranslate2\converters\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\ctranslate2\specs\attention_spec.py to attention_spec.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\ctranslate2\specs\common_spec.py to common_spec.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\ctranslate2\specs\model_spec.py to model_spec.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\ctranslate2\specs\transformer_spec.py to transformer_spec.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\ctranslate2\specs\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\ctranslate2\version.py to version.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\ctranslate2\__init__.py to __init__.cpython-38.pyc
creating stub loader for ctranslate2\translator.cp38-win_amd64.pyd
byte-compiling build\bdist.win-amd64\egg\ctranslate2\translator.py to translator.cpython-38.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying ctranslate2.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying ctranslate2.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying ctranslate2.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying ctranslate2.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying ctranslate2.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying ctranslate2.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
ctranslate2.__pycache__.translator.cpython-38: module references __file__
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing ctranslate2-2.3.2-py3.8-win-amd64.egg
removing 'r:\program files (x86)\anaconda3\envs\protocolpackages\lib\site-packages\ctranslate2-2.3.2-py3.8-win-amd64.eggcreating r:\program files (x86)\anaconda3\envs\protocolpackages\lib\site-packages\ctranslate2-2.3.2-py3.8-win-amd64.egg
Extracting ctranslate2-2.3.2-py3.8-win-amd64.egg to r:\program files (x86)\anaconda3\envs\protocolpackages\lib\site-packages
ctranslate2 2.3.2 is already the active version in easy-install.pth
Installing ct2-fairseq-converter-script.py script to R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\Scripts
Installing ct2-fairseq-converter.exe script to R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\Scripts
Installing ct2-opennmt-py-converter-script.py script to R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\Scripts
Installing ct2-opennmt-py-converter.exe script to R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\Scripts
Installing ct2-opennmt-tf-converter-script.py script to R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\Scripts
Installing ct2-opennmt-tf-converter.exe script to R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\Scripts

Installed r:\program files (x86)\anaconda3\envs\protocolpackages\lib\site-packages\ctranslate2-2.3.2-py3.8-win-amd64.egg
Processing dependencies for ctranslate2==2.3.2
Searching for numpy==1.21.2
Best match: numpy 1.21.2
Adding numpy 1.21.2 to easy-install.pth file
Installing f2py-script.py script to R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\Scripts
Installing f2py.exe script to R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\Scripts

Using r:\program files (x86)\anaconda3\envs\protocolpackages\lib\site-packages
Finished processing dependencies for ctranslate2==2.3.2
```
```
(ProtocolPackages) PS R:\Ressourcen\Pakete\CTranslate2\python> pip install ctranslate2
Requirement already satisfied: ctranslate2 in r:\program files (x86)\anaconda3\envs\protocolpackages (2.3.2)
Requirement already satisfied: numpy in r:\program files (x86)\anaconda3\envs\protocolpackages\lib\site-packages (from ctranslate2) (1.21.2)
```

But when trying to use the module, the following error is raised:
```
Traceback (most recent call last):
    File "R:/Workspaces/PycharmProjects/ScrapingProtocols/news_scraping_protocol/workbench.py", line 9, in <module>
		from news_scraping_protocol.utils import translation_utils
    File "R:\Workspaces\PycharmProjects\ScrapingProtocols\news_scraping_protocol\utils\translation_utils.py", line 19, in <module>
		from argostranslate import package, translate
    File "R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\lib\site-packages\argostranslate\translate.py", line 3, in <module>
		import ctranslate2
    File "R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\lib\site-packages\ctranslate2-2.3.2-py3.8-win-amd64.egg\ctranslate2\__init__.py", line 2, in <module>
		from ctranslate2.translator import Translator
ImportError: DLL load failed while importing translator: Das angegebene Modul wurde nicht gefunden.
```

It took a long time to handle a lot of errors while building and installing engine and module on windows, so I have no idea, where to start with fixing this problem. Since I am not good with c++ and building stuff, I more or less solved one error message at a time. I recorded a protocol of the changes, if useful for finding the cause(s) of this problem.

While I am at it, will there be a windows compatible wheel, like the one created for macOS?
And what are the best CMake building arguments to get a working build on Windows. 

Thank your for your time.

**Comment by guillaumekln** [comment]
Hi,

> `ImportError: DLL load failed while importing translator`

Most likely Python does not find the library `libctranslate2.dll` that was compiled with CMake. Can you try using the Python function [`os.add_dll_directory`](https://docs.python.org/3/library/os.html#os.add_dll_directory) before importing CTranslate2?

> While I am at it, will there be a windows compatible wheel, like the one created for macOS?

There are currently no plans for Windows wheels, but we welcome external contributions.

> And what are the best CMake building arguments to get a working build on Windows.

@panosk Do you have any recommendation specific to Windows here?

**Comment by AlHering** [comment]
Thank you for your fast and useful reponse.

I think, I shipped around the problem, solvable with `os.add_dll_directory`, by adding the folders of the CTranslate2 installation to my system's PATH variable.

I built two separate versions of the engine and the python module afterwards and put them in the same folders and added them to PATH. 

Version 1 was made with `-DWITH_DNNL=ON`, version 2 with no arguments.
Version 1 suffered from the error above, version 2 did not. Version 1 could also not be fixed with using os.add_dll_directory to link the ctranslate2.dll (that's what it is called in my install, should it be renamed?) folder.

Both build- and installation-processes looked fine and the files although of slightly different size, are also the same across both builds:
```
bin/ctranslate2.dll
bin/translate.exe
include/ctranslate2/ with lots of stuff c++ header files
lib/ctranslate2.lib
```

Version 2 raises a new error but gets further than version 1 did.
```
Traceback (most recent call last):
  File "R:/Workspaces/PycharmProjects/ScrapingProtocols/news_scraping_protocol/workbench.py", line 11, in <module>
    print(translation_utils.translate_offline("Please work!", "en", "de"))
  File "R:\Workspaces\PycharmProjects\ScrapingProtocols\news_scraping_protocol\utils\translation_utils.py", line 156, in translate_offline
    translation = offline_translators[language_dict["offline"][from_language]][
  File "R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\lib\site-packages\argostranslate\translate.py", line 185, in translate
    translated_paragraph = self.underlying.translate(paragraph)
  File "R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\lib\site-packages\argostranslate\translate.py", line 115, in translate
    apply_packaged_translation(self.pkg, paragraph))
  File "R:\Program Files (x86)\Anaconda3\envs\ProtocolPackages\lib\site-packages\argostranslate\translate.py", line 205, in apply_packaged_translation
    translator = ctranslate2.Translator(model_path)
ValueError: unsupported device 
```

But that error could also be raised because of stuff on the [ArgosTranslate](https://github.com/argosopentech/argos-translate) side of things. 

Is there a way to list all working device options of the current CTranslate2 install?
Again, thank you very much for your time. I appreciate it.

**Comment by panosk** [comment]
The CTranslate2 library (`ctranslate2.dll`) builds fine with no errors under Windows and with no special configuration. From then on, you have to fiddle around all the Windows weirdness if you want to use the cli client. I haven't built or used the client for a long time, but one trick you can do in order to find all the required dlls is to double click the translate.exe executable and then you will get messages with the missing dlls.  Depending on the options you use with CMake, you will need `dnnl.dll` (if `WITH_DNNL=ON`) , `libomp5md.dll` (if `WITH_MKL=ON`) and so on. Also, in order to test the client, it's best to open a Native Tools Command Prompt for VS 2019 instead of bash or other terminals, as the developer command prompt will load automatically all the required CRT stuff.

**Comment by guillaumekln** [comment]
Thanks Panos.

> `ValueError: unsupported device`

This looks like a usage error since the default device should be "cpu", but here it looks like the device is set to an empty string. Can you check in your application of the device value is changed somewhere? I see that Argos has a device setting.

**Comment by AlHering** [comment]
Thank you both for your time and help!

> find all the required dlls is to double click the translate.exe executable
This allowed the previously mentioned version 1 of the builds to work. So it gets to the same new error message as version 2.

> it's best to open a Native Tools Command Prompt for VS 2019
I will build my next try with the developer command prompt from the start.

> Can you check in your application if the device value is changed somewhere?
Thank you, I found the interfacing parts in the code. The CTranslate2 stuff seems to be hidden inside the `translator.cp38-win_amd64.pyd` file. But instantiating `ctranslate2.Translator()` without arguments resultet in 
`ctranslate2.translator.Translator(model_path: str, device: str = 'cpu', *, device_index: Union[int, List[int]] = 0, compute_type: Union[str, Dict[str, str]] = 'default', inter_threads: int = 1, intra_threads: int = 0)`

Since the error occures at `ctranslate2.Translator(model_path)`  I would guess, that the device string gets correctly set. 
I am wondering about the `*` as next parameter, since it does not match the
```
TranslatorWrapper(const std::string& model_path,
                    const std::string& device,
                    const std::variant<int, std::vector<int>>& device_index,
                    const StringOrMap& compute_type,
                    size_t inter_threads,
                    size_t intra_threads)
```
from CTranslate2.

However, you two helped me a great bit in localizing and solving the initial problem.
I guess, therefor the issue can be closed.

Thanks again for your time!

**Comment by guillaumekln** [comment]
> I am wondering about the * as next parameter, since it does not match

It means the following arguments are keyword-only arguments. See https://www.python.org/dev/peps/pep-3102/.

**Comment by AlHering** [comment]
> 
> 
> > I am wondering about the * as next parameter, since it does not match
> 
> It means the following arguments are keyword-only arguments. See https://www.python.org/dev/peps/pep-3102/.

Thanks again. That kind of filled a serious gap in my python knowledge.

**Comment by Doko-Demo-Doa** [comment]
@AlHering  Sorry for digging this up but I bumped into a similar error:

```
PS D:\Projects\CPP\CTranslate2\python> python .\setup.py build
running build
running build_py
running build_ext
building 'ctranslate2.translator' extension
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\phamv\AppData\Local\Programs\Python\Python39\lib\site-packages\pybind11\include -IC:\Users\phamv\AppData\Local\Programs\Python\Python39\include -IC:\Users\phamv\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /EHsc /Tptranslator.cc /Fobuild\temp.win-amd64-3.9\Release\translator.obj -std=c++17
cl : Command line warning D9002 : ignoring unknown option '-std=c++17'
translator.cc
The contents of <optional> are available only with C++17 or later.
The contents of <variant> are available only with C++17 or later.
translator.cc(11): fatal error C1083: Cannot open include file: 'ctranslate2/translator_pool.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

How can I let python know the path to `include` folder? I tried to set `PATH`, `LD_LIBRARY_PATH` and `CPLUS_INCLUDE_PATH` so far, no luck still.

I'm on Windows 10, Visual Studio 2019 and Python 3.8.

**Comment by AlHering** [comment]
@Doko-Demo-Doa No problem at all, however, I tinkered around for quite some time so I am not sure if I ever ran into a similar issue.
Did building ctranslate2 manually with Visual Studio run into any issues?

If not, you could try adjusting the `ctranslate2/python/setup.py`: 
You can manually add inlcude and library directories with appending them to `include_dirs` / `library_dirs`, after the `_maybe_add_library_root("CTRANSLATE2")` statement.
I tinkered around till it looked something like this for my ctranslate2 installation path:
`
_maybe_add_library_root("CTRANSLATE2")
library_dirs.append("R:\\Ressourcen\\Installationen\\ctranslate2\\lib")
include_dirs.append("R:\\Ressourcen\\Installationen\\ctranslate2\\include\\ctranslate2")
include_dirs.append("R:\\Ressourcen\\Installationen\\ctranslate2\\include")
`

I hope this information is of help to you.

**Comment by Doko-Demo-Doa** [comment]
Thank you very much. I can build ctranslate2 without issue with Visual Studio toolchain (using Cmake, not the VS IDE). The problem occurs when I try to `python setup.py build` only.

**Comment by guillaumekln** [comment]
This warning is important:

```text
cl : Command line warning D9002 : ignoring unknown option '-std=c++17'
translator.cc
The contents of <optional> are available only with C++17 or later.
The contents of <variant> are available only with C++17 or later.
```

In `setup.py`, you should update the CFLAGS for MSVC: use `/std:c++17` instead of `-std=c++17`.

**Comment by guillaumekln** [comment]
FYI, #620 is adding Python wheels for Windows.
