### ISSUE TITLE
child 'bpe.sentencepiece_model' is not Optional

### ISSUE THREAD

**Issue by Zaoyee** [OpenNMT/CTranslate2#663]
Thanks for your work. When I converting Fairseq to CTranslate, I got error like this. Is there any way to fix it?

```
Traceback (most recent call last):
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 513, in _apply_overrides_to_config
    OmegaConf.update(cfg, key, value, merge=True)
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/omegaconf/omegaconf.py", line 613, in update
    root.__setattr__(last_key, value)
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 285, in __setattr__
    raise e
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 282, in __setattr__
    self.__set_impl(key, value)
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 266, in __set_impl
    self._set_item_impl(key, value)
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 398, in _set_item_impl
    self._validate_set(key, value)
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 143, in _validate_set
    self._validate_set_merge_impl(key, value, is_assign=True)
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 159, in _validate_set_merge_impl
    cause=ValidationError("child '$FULL_KEY' is not Optional"),
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ValidationError: child 'bpe.sentencepiece_model' is not Optional
        full_key: bpe.sentencepiece_model
        reference_type=Optional[SentencepieceConfig]
        object_type=SentencepieceConfig

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/bin/ct2-fairseq-converter", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/ctranslate2/converters/fairseq.py", line 251, in main
    converter.convert_from_args(args)
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/ctranslate2/converters/converter.py", line 35, in convert_from_args
    force=args.force,
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/ctranslate2/converters/converter.py", line 45, in convert
    model_spec = self._load()
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/ctranslate2/converters/fairseq.py", line 102, in _load
    checkpoint = checkpoint_utils.load_checkpoint_to_cpu(self._model_path)
  File "/mnt/data/Libraries/fairseq/fairseq/checkpoint_utils.py", line 338, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/mnt/data/Libraries/fairseq/fairseq/checkpoint_utils.py", line 670, in _upgrade_state_dict
    state["cfg"] = convert_namespace_to_omegaconf(state["args"])
  File "/mnt/data/Libraries/fairseq/fairseq/dataclass/utils.py", line 389, in convert_namespace_to_omegaconf
    composed_cfg = compose("config", overrides=overrides, strict=False)
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/hydra/experimental/compose.py", line 37, in compose
    with_log_configuration=False,
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 512, in compose_config
    from_shell=from_shell,
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 156, in load_configuration
    from_shell=from_shell,
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 277, in _load_configuration
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File "/home/ubuntu481/anaconda3/envs/ygm_py3.6/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 522, in _apply_overrides_to_config
    ) from ex
hydra.errors.ConfigCompositionException: Error merging override bpe.sentencepiece_model=null

```

**Comment by Zaoyee** [comment]
I understand the problem was the way I trained the model. After I fix it, I still face another problem with error
```
ValueError: The model you are trying to convert is not supported by CTranslate2. We identified the following reasons:

- Option --layernorm-embedding is not supported
```

**Comment by guillaumekln** [comment]
The last error is quite explicit. You trained the model with the option `--layernorm-embedding`, but this option is not yet implemented by CTranslate2.

**Comment by Zaoyee** [comment]
> The last error is quite explicit. You trained the model with the option `--layernorm-embedding`, but this option is not yet implemented by CTranslate2.

Yes, I retrained the model without `layernorm`, and it works.
