### ISSUE TITLE
RuntimeError: Unable to open file 'target_vocabulary.txt' in model 'end_output/'

### ISSUE THREAD

**Issue by Jourdelune** [OpenNMT/CTranslate2#698]
Hello, on version 2.4 of ctranslate, I can launch the translations, however on version 2.11, I have this error that appears:
```
[2022-01-21 20:54:12 +0100] [1697] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/pi/.local/lib/python3.9/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/Api.py", line 35, in <module>
    model_class = ModelInference()
  File "/home/pi/Api.py", line 15, in __init__
    self.translator = ctranslate2.Translator("end_output/", device="cpu", inter_threads=1, intra_threads=2, compute_type="auto")
RuntimeError: Unable to open file 'target_vocabulary.txt' in model 'end_output/'
```

I understood the error but on version 2.4, with the same file, everything works (however not on the same platform, I try to run ctranslate2 on a raspberry pi so I can only run version 11, but on my vps, with the same file and version 2.4 of ctranslate2, I don't have this error).
Here are the files I have:
```
pi@raspberrypi:~ $ ls end_output
model.bin  source_vocabulary.txt
```

Has there been an update that does not require new files, and if so how to get them, or is it a bug.
Sincerely

**Comment by panosk** [comment]
Hi,
I'm not sure how it works on 2.4 without a target vocabulary. Are you sure you are using the very same model directory? I'm pretty sure you need either both `source_vocabulary.txt` and `target_vocabulary.txt` or just `shared_vocabulary.txt`.

**Comment by Jourdelune** [comment]
Totally sure, I compile m2m100 which gives me these two files, I have no other output

**Comment by Jourdelune** [comment]
Ah, yet that's what I get. Strange...
![image](https://user-images.githubusercontent.com/64205064/150640884-08d8b058-755c-4e0f-99a8-d84eb67a5a84.png)

**Comment by guillaumekln** [comment]
Now the model structure is correct.

**Comment by Jourdelune** [comment]
Uh it's the same one :D

**Comment by guillaumekln** [comment]
No. In the first message you had `source_vocabulary.txt`, now you have `shared_vocabulary.txt`.

**Comment by Jourdelune** [comment]
oh okayy, thanks you :D
