### ISSUE TITLE
error during model conversion

### ISSUE THREAD

**Issue by panosk** [OpenNMT/CTranslate2#78]
On OS X Catalina, now I get this error when I try to convert a model:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/panos/Development/CTranslate2/python/ctranslate2/bin/opennmt_tf_converter.py", line 23, in <module>
    main()
  File "/Users/panos/Development/CTranslate2/python/ctranslate2/bin/opennmt_tf_converter.py", line 19, in main
    tgt_vocab=args.tgt_vocab).convert_from_args(args)
  File "/Users/panos/Development/CTranslate2/python/ctranslate2/converters/converter.py", line 39, in convert_from_args
    force=args.force)
  File "/Users/panos/Development/CTranslate2/python/ctranslate2/converters/converter.py", line 53, in convert
    src_vocab, tgt_vocab = self._load(model_spec)
  File "/Users/panos/Development/CTranslate2/python/ctranslate2/converters/opennmt_tf.py", line 107, in _load
    tgt_vocab=self._tgt_vocab)
  File "/Users/panos/Development/CTranslate2/python/ctranslate2/converters/opennmt_tf.py", line 57, in load_model
    src_vocab = _get_asset_path(imported.examples_inputter.features_inputter)
AttributeError: 'AutoTrackable' object has no attribute 'examples_inputter'
```

**Comment by guillaumekln** [comment]
What model are you trying to convert? Was it released with TensorFlow v1?

**Comment by panosk** [comment]
Yes, v1.

**Comment by panosk** [comment]
I guess I need to convert it. Is there a script for that?

**Comment by guillaumekln** [comment]
Currently it is required to run the script with same major TensorFlow version as the one used to export the model (e.g. use TensorFlow 1.x to convert a model exported with TensorFlow 1.x). On the other hand, checkpoint conversion works with any TensorFlow version.

**Comment by panosk** [comment]
It makes sense, thanks. I switched to TensorFlow 1.15 and converted the model.
