### ISSUE TITLE
How to use Bart models?

### ISSUE THREAD

**Issue by juliensalinas** [OpenNMT/CTranslate2#816]
Thanks so much for this amazing library. This is very useful!

I am trying to use Bart models but I'm getting this error: `AttributeError: 'BartConfig' object has no attribute 'normalize_embedding'`

Example:

```ct2-transformers-converter --model facebook/bart-large-cnn  --output_dir bart_large_cnn```

Returns the following error:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/ct2-transformers-converter", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 384, in main
    converter.convert_from_args(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 63, in _load
    return loader(self._model_name_or_path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 86, in __call__
    spec = self.get_model_spec(model)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ctranslate2/converters/transformers.py", line 147, in get_model_spec
    layernorm_embedding=model.config.normalize_embedding,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/configuration_utils.py", line 253, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'BartConfig' object has no attribute 'normalize_embedding'
```

Am I missing something?

Thanks!

**Comment by guillaumekln** [comment]
Hi,

We tested `bart-base`, but not `bart-large-cnn` which uses an older model configuration. The linked PR should fix this conversion error (you could apply the changes locally to unblock the conversion error). I also added a usage example in the documentation.

Thanks for reporting this issue!

**Comment by juliensalinas** [comment]
Woooh that was quick!

I works like a charm, thanks so much @guillaumekln .
Thanks for the updated README too!
