### ISSUE TITLE
Converter: Fairseq multilingual_transformer - shape size mismatch

### ISSUE THREAD

**Issue by ymoslem** [OpenNMT/CTranslate2#837]
Hello! This is a Fairseq `multilingual_transformer` model I cannot convert [[download link](https://drive.google.com/file/d/1MDlU95re8cs9qd8p1ItXILgtmJE7tS07/view?usp=sharing)]. Is there an easy fix for this? Thanks!

### Command
```
ct2-fairseq-converter --model_path en_de_nmt_model.pt --data_dir nmt_dicts_en_de --output_dir ct2_deen_model
```

### Error
```
2022-06-15 23:37:26 | INFO | fairseq.tasks.multilingual_translation | [de] dictionary: 67706 types
2022-06-15 23:37:26 | INFO | fairseq.tasks.multilingual_translation | [en] dictionary: 67706 types
Traceback (most recent call last):
  File "/home/user/.local/bin/ct2-fairseq-converter", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/ctranslate2/converters/fairseq.py", line 340, in main
    converter.convert_from_args(args)
  File "/home/user/.local/lib/python3.7/site-packages/ctranslate2/converters/converter.py", line 54, in convert_from_args
    force=args.force,
  File "/home/user/.local/lib/python3.7/site-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/home/user/.local/lib/python3.7/site-packages/ctranslate2/converters/fairseq.py", line 170, in _load
    model.load_state_dict(checkpoint["model"])
  File "/home/user/.local/lib/python3.7/site-packages/fairseq/models/multilingual_transformer.py", line 205, in load_state_dict
    super().load_state_dict(state_dict_subset, strict=strict, model_cfg=model_cfg)
  File "/home/user/.local/lib/python3.7/site-packages/fairseq/models/fairseq_model.py", line 470, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/user/.local/lib/python3.7/site-packages/fairseq/models/fairseq_model.py", line 128, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1498, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MultilingualTransformerModel:
	size mismatch for models.en-de.encoder.embed_tokens.weight: copying a param with shape torch.Size([67707, 512]) from checkpoint, the shape in current model is torch.Size([67706, 512]).
	size mismatch for models.en-de.decoder.embed_tokens.weight: copying a param with shape torch.Size([67707, 512]) from checkpoint, the shape in current model is torch.Size([67706, 512]).
	size mismatch for models.en-de.decoder.output_projection.weight: copying a param with shape torch.Size([67707, 512]) from checkpoint, the shape in current model is torch.Size([67706, 512]).

```

### Packages
```
ctranslate2==2.19.0
fairseq==0.12.1
torch==1.11.0+cu113
```

**Comment by guillaumekln** [comment]
Hi,

It looks like the model was trained with a [custom version](https://github.com/ZhenYangIACAS/WeTS) of Fairseq. Did you manage to run this model with your Fairseq version?

The issue is that the vocabularies and model configuration do not seem to be consistent with the model weights. The vocabulary files on disk have 67700 lines and Fairseq automatically adds 6 tokens:

* the special tokens `<s>`, `<pad>`, `</s>`, `<unk>`
* the language tokens `__de__`, `__en__` (generated from the model configuration `lang_pairs=['en-de', 'de-en']`)

The total vocabulary size is then 67706 but the model weights expect 1 additional token. What is the missing token? I'm wondering if there should be an additional `__fr__` token since there is also a French vocabulary, but the fr language is not mentioned in the model configuration.

**Comment by ymoslem** [comment]
I think you are right. Thank you very much for the pointer, Guillaume!
