### ISSUE TITLE
NLLB: module 'transformers' has no attribute 'AutoConfig'

### ISSUE THREAD

**Issue by juliensalinas** [OpenNMT/CTranslate2#886]
Hello @guillaumekln, thanks for adding the NLLB support.

I just tried the model conversion: `ct2-transformers-converter --model facebook/nllb-200-distilled-600M --output_dir nllb-200-distilled-600M`

It returns the following:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 449, in <module>
    main()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 445, in main
    converter.convert_from_args(args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 51, in _load
    config = transformers.AutoConfig.from_pretrained(self._model_name_or_path)
AttributeError: module 'transformers' has no attribute 'AutoConfig'
```

Here are the versions I'm using:

- ctranslate2: 2.21.0
- transformers: 4.21.0
- torch: 1.12.0

Am I missing something obvious?

Thanks!!

**Comment by juliensalinas** [comment]
PS: I notice it's happening with any model I'm trying to convert. Not only with NLLB. So there must be something wrong with my installation maybe...

**Comment by guillaumekln** [comment]
Hi,

Maybe you have directory named `transformers` or Python file named `transformers.py` in the current directory?

If not, can you double-check the Transformers version?

```
$ python3 -c "import transformers; print(transformers.__version__)"
4.21.0
```

**Comment by juliensalinas** [comment]
You are absolutely right. Really sorry about that!
Thanks a lot.
