### ISSUE TITLE
NLLB: 'NllbTokenizer' object has no attribute 'num_madeup_words'

### ISSUE THREAD

**Issue by juliensalinas** [OpenNMT/CTranslate2#887]
The model conversion works for NLLB Distilled 600M, but it fails for NLLB 3.3B:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/./ct2-transformers-converter", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 445, in main
    converter.convert_from_args(args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 62, in _load
    return loader(self._model_name_or_path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 87, in __call__
    tokens = self.get_vocabulary(model, tokenizer)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ctranslate2/converters/transformers.py", line 307, in get_vocabulary
    num_madeup_words = tokenizer.num_madeup_words
AttributeError: 'NllbTokenizer' object has no attribute 'num_madeup_words'
```

Thanks in advance for your help :)

**Comment by guillaumekln** [comment]
Thank you for testing the different versions.

Apparently the configuration field `tokenizer_class`  is only defined in `facebook/nllb-200-distilled-600M`. I wrongly assumed the field to be present in all versions.

I will make a quick fix and release a new version just after.

**Comment by juliensalinas** [comment]
It works like a charm, thanks!
